name: Tests
on: push

jobs:
  testsAndCoverage:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm install
      # - name: Run tests
      #   run: npm run test:ci
      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v1
      #   if: always()
      #   with:
      #     files: junit.xml
      - name: Publish Coverage Results
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # annotations: all
          test-command: npm run test:ci
          # coverage-file: coverage/coverage-final.json
          # skip-step: all
