name: Tests
on: push

jobs:
  testsAndCoverage:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm run test:ci
      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v1
      #   if: always()
      #   with:
      #     files: junit.xml
      - name: Publish Coverage Results
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          annotations: all
          test-script: npm run test:ci